name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release on Version Bump
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2  # Updated version

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0  # Updated version
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Get Version from package.json
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Create GitHub Release Tag
        uses: softprops/action-gh-release@v2.2.2  # Updated version
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
