name: Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed for GitHub Tag Action to create tags/releases

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated version

      - name: GitHub Tag Action
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
